[package]
name = "protondrive-tauri"
version = "1.0.0"
description = "Proton Drive desktop client"
authors = ["Proton AG"]
license = "AGPL-3.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5", features = ["api-all", "notification", "webkit2gtk-4.1"] }
tokio = { version = "1", features = ["full"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
